# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b9XYV98vmJ8mI8-iZz-zxBaTfambfSOU
"""

# importing Numpy package
import numpy as np
import math as m
x=60
y=45
z=30
# creating a 2X2 Numpy matrix
n_array = np.array([[m.tan(x*np.pi/180), 1/np.tan(x*np.pi/180),1],[np.tan(y*np.pi/180), 1/np.tan(y*np.pi/180),1],[np.tan(z*np.pi/180), 1/np.tan(z*np.pi/180),1] ])

# Displaying the Matrix
print(" Matrix is:")
print(n_array)

# calculating the determinant of matrix
det =0.5*np.linalg.det(n_array)

print("\nDeterminant of given 3X3 matrix:")
print(float(det))

# importing Numpy package
import numpy as np

a=4*np.sin(15*np.pi/180)*np.sin(15*np.pi/180)*np.sin(-30*np.pi/180)
print(a)
b=np.sin(120*np.pi/180)*np.sin(90*np.pi/180)*np.sin(60*np.pi/180)
print(b)
c=a/b
print(c)